# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@rules_pkg//:mappings.bzl", "pkg_files")

package(default_visibility = ["//visibility:public"])

pkg_files(
    name = "keydb_pkg",
    srcs = [
        "//coordinator/terraform/aws/modules/keydb",
    ],
    prefix = "modules/keydb",
    strip_prefix = ".",
)

pkg_files(
    name = "keyjobqueue_pkg",
    srcs = [
        "//coordinator/terraform/aws/modules/keyjobqueue",
    ],
    prefix = "modules/keyjobqueue",
    strip_prefix = ".",
)

pkg_files(
    name = "keymanagementroleprovider_pkg",
    srcs = [
        "//coordinator/terraform/aws/modules/keymanagementroleprovider",
    ],
    prefix = "modules/keymanagementroleprovider",
    strip_prefix = ".",
)

pkg_files(
    name = "keystoragedashboard_pkg",
    srcs = [
        "//coordinator/terraform/aws/modules/keystoragedashboard",
    ],
    prefix = "modules/keystoragedashboard",
    strip_prefix = ".",
)

pkg_files(
    name = "multipartykeygeneration_service_pkg",
    srcs = [
        "//coordinator/terraform/aws/modules/multipartykeygenerationservice",
    ],
    prefix = "modules/multipartykeygenerationservice",
    strip_prefix = ".",
)

pkg_files(
    name = "keystorageservice_pkg",
    srcs = [
        "//coordinator/terraform/aws/modules/keystorageservice",
    ],
    prefix = "modules/keystorageservice",
    strip_prefix = ".",
)

pkg_files(
    name = "privacybudgetdb_pkg",
    srcs = [
        "//coordinator/terraform/aws/modules/privacybudgetdb",
    ],
    prefix = "modules/privacybudgetdb",
)

pkg_files(
    name = "privacybudgetservice_pkg",
    srcs = [
        "//coordinator/terraform/aws/modules/privacybudgetservice",
    ],
    prefix = "modules/privacybudgetservice",
)

pkg_files(
    name = "distributed_pbs_access_policy_pkg",
    srcs = [
        "//coordinator/terraform/aws/modules/distributedpbs_access_policy",
    ],
    prefix = "modules/distributedpbs_access_policy",
)

pkg_files(
    name = "distributed_pbs_alarms_pkg",
    srcs = [
        "//coordinator/terraform/aws/modules/distributedpbs_alarms",
    ],
    prefix = "modules/distributedpbs_alarms",
)

pkg_files(
    name = "distributed_pbs_auth_db_pkg",
    srcs = [
        "//coordinator/terraform/aws/modules/distributedpbs_auth_db",
    ],
    prefix = "modules/distributedpbs_auth_db",
)

pkg_files(
    name = "distributed_pbs_auth_records_pkg",
    srcs = [
        "//coordinator/terraform/aws/modules/distributedpbs_auth_records",
    ],
    prefix = "modules/distributedpbs_auth_records",
)

pkg_files(
    name = "distributed_pbs_auth_service_pkg",
    srcs = [
        "//coordinator/terraform/aws/modules/distributedpbs_auth_service",
    ],
    prefix = "modules/distributedpbs_auth_service",
)

pkg_files(
    name = "distributed_pbs_beanstalk_environment_pkg",
    srcs = [
        "//coordinator/terraform/aws/modules/distributedpbs_beanstalk_environment",
    ],
    prefix = "modules/distributedpbs_beanstalk_environment",
)

pkg_files(
    name = "distributed_pbs_beanstalk_environment_files_pkg",
    srcs = [
        "//coordinator/terraform/aws/modules/distributedpbs_beanstalk_environment/files",
    ],
    prefix = "modules/distributedpbs_beanstalk_environment/files",
)

pkg_files(
    name = "distributed_pbs_beanstalk_storage_pkg",
    srcs = [
        "//coordinator/terraform/aws/modules/distributedpbs_beanstalk_storage",
    ],
    prefix = "modules/distributedpbs_beanstalk_storage",
)

pkg_files(
    name = "distributed_pbs_container_registry_pkg",
    srcs = [
        "//coordinator/terraform/aws/modules/distributedpbs_container_registry",
    ],
    prefix = "modules/distributedpbs_container_registry",
)

pkg_files(
    name = "distributed_pbs_storage_pkg",
    srcs = [
        "//coordinator/terraform/aws/modules/distributedpbs_storage",
    ],
    prefix = "modules/distributedpbs_storage",
)

pkg_files(
    name = "encryptionkey_service_pkg",
    srcs = [
        "//coordinator/terraform/aws/modules/encryptionkeyservice",
    ],
    prefix = "modules/encryptionkeyservice",
    strip_prefix = ".",
)

pkg_files(
    name = "privatekeydomainprovider_pkg",
    srcs = [
        "//coordinator/terraform/aws/modules/privatekeydomainprovider",
    ],
    prefix = "modules/privatekeydomainprovider",
    strip_prefix = ".",
)

pkg_files(
    name = "publickeyhostingcloudfront_pkg",
    srcs = [
        "//coordinator/terraform/aws/modules/publickeyhostingcloudfront",
    ],
    prefix = "modules/publickeyhostingcloudfront",
    strip_prefix = ".",
)

pkg_files(
    name = "publickeyhostingservice_pkg",
    srcs = [
        "//coordinator/terraform/aws/modules/publickeyhostingservice",
    ],
    prefix = "modules/publickeyhostingservice",
    strip_prefix = ".",
)

pkg_files(
    name = "sslcertificateprovider_pkg",
    srcs = [
        "//coordinator/terraform/aws/modules/sslcertificateprovider",
    ],
    prefix = "modules/sslcertificateprovider",
    strip_prefix = ".",
)

pkg_files(
    name = "multipartykeygenerationservice_pkg",
    srcs = [
        "//coordinator/terraform/aws/modules/multipartykeygenerationservice",
    ],
    prefix = "modules/multipartykeygenerationservice",
    strip_prefix = ".",
)

pkg_files(
    name = "privacybudgetdashboard_pkg",
    srcs = [
        "//coordinator/terraform/aws/modules/privacybudgetdashboard",
    ],
    prefix = "modules/privacybudgetdashboard",
    strip_prefix = ".",
)

pkg_files(
    name = "privacybudgetdomainprovider_pkg",
    srcs = [
        "//coordinator/terraform/aws/modules/privacybudgetdomainprovider",
    ],
    prefix = "modules/privacybudgetdomainprovider",
    strip_prefix = ".",
)

pkg_files(
    name = "vpc_v2_pkg",
    srcs = [
        "//coordinator/terraform/aws/modules/vpc_v2",
    ],
    prefix = "modules/vpc_v2",
    strip_prefix = ".",
)

pkg_files(
    name = "apigateway_pkg",
    srcs = [
        "//coordinator/terraform/aws/modules/apigateway",
    ],
    prefix = "modules/apigateway",
    strip_prefix = ".",
)

pkg_files(
    name = "shared_bucketprovider_pkg",
    srcs = [
        "//coordinator/terraform/aws/modules/shared/bucketprovider",
    ],
    prefix = "modules/shared/bucketprovider",
    strip_prefix = ".",
)

pkg_files(
    name = "shared_lambda_roles_pkg",
    srcs = [
        "//coordinator/terraform/aws/modules/shared/lambda_roles",
    ],
    prefix = "modules/shared/lambda_roles",
    strip_prefix = ".",
)

pkg_files(
    name = "shared_workerenclaveencryptionkey_pkg",
    srcs = [
        "//coordinator/terraform/aws/modules/shared/workerenclaveencryptionkey",
    ],
    prefix = "modules/shared/workerenclaveencryptionkey",
    strip_prefix = ".",
)

pkg_files(
    name = "bazel_module_pkg",
    srcs = [
        "//coordinator/terraform/aws/modules/bazel",
    ],
    prefix = "modules/bazel",
    strip_prefix = ".",
)

pkg_files(
    name = "unifiedkeyhostingdashboard_pkg",
    srcs = [
        "//coordinator/terraform/aws/modules/unifiedkeyhostingdashboard",
    ],
    prefix = "modules/unifiedkeyhostingdashboard",
    strip_prefix = ".",
)

pkg_files(
    name = "publickeyhostingdashboard_pkg",
    srcs = [
        "//coordinator/terraform/aws/modules/publickeyhostingdashboard",
    ],
    prefix = "modules/publickeyhostingdashboard",
    strip_prefix = ".",
)
