# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

workspace(name = "com_google_scp_roma_getting_started")

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "com_google_scp",
    #v0.83.0
    commit = "797525e17bcc1643602c898eb97dbd60e8c3acb9",
    remote = "https://github.com/privacysandbox/control-plane-shared-libraries.git",
)

load("@com_google_scp//build_defs/shared:bazel_rules_python.bzl", "bazel_rules_python")

bazel_rules_python()

load("@com_google_scp//build_defs/cc/shared:cc_utils.bzl", "cc_utils")

cc_utils()

load("@com_google_scp//build_defs/shared:absl.bzl", "absl")

absl()

load("@com_google_scp//build_defs/shared:protobuf.bzl", "protobuf")

protobuf()

load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")

protobuf_deps()

load("@com_google_scp//build_defs/cc:roma.bzl", "roma_dependencies")

roma_dependencies("@com_google_scp")

load(
    "@com_google_sandboxed_api//sandboxed_api/bazel:llvm_config.bzl",
    "llvm_disable_optional_support_deps",
)

# Must be right after roma_dependencies
load(
    "@com_google_sandboxed_api//sandboxed_api/bazel:sapi_deps.bzl",
    "sapi_deps",
)

llvm_disable_optional_support_deps()

sapi_deps()
