output "name_servers" {
  description = "Domain record nameservers associated with the zone generated by this module. To be added as NS records to the DNS provider which manages var.domain_name."
  value       = resource.aws_route53_zone.hosted_zone.name_servers
}
