load("@rules_pkg//:mappings.bzl", "pkg_filegroup")

package(default_visibility = ["//visibility:public"])

pkg_filegroup(
    name = "applications_pkg",
    srcs = [
        "//operator/terraform/gcp/applications/jobservice",
    ],
    prefix = "applications",
)
